theme: jekyll-theme-hacker
title: Brian Howard's homepage
description: I share thoughts and experiences on computers, coding, history, arts, sports, and more. As a self-taught programmer with an artist's perspective rather than a traditional CS background, I offer a unique take on coding topics, particularly in game development.